### ISSUE TITLE
Crypto is broken after last release

### ISSUE THREAD

**Issue by drewpearce** [Legobot/legos.stocks#15]
Searching for cryptocurrencies appears to be borked after last release. Not sure why. Will work on it ASAP.

`Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/drew/virtualenvs/legobot/local/lib/python3.6/site-packages/Legobot/Lego.py", line 30, in run
    self.handler(self.message)
  File "/home/drew/virtualenvs/legobot/local/lib/python3.6/site-packages/legos/cryptocurrency.py", line 32, in handle
    self.reply(message, self.lookup_symbol(query), opts)
  File "/home/_/virtualenvs/legobot/local/lib/python3.6/site-packages/legos/cryptocurrency.py", line 46, in lookup_symbol
    if 'There is no data for the symbol' in api_response['Message']:
KeyError: 'Message'
`

**Comment by drewpearce** [comment]
resolved by referenced commit
